{
  "swagger": "2.0",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "paths": {
    "/api/v1/concerts": {
      "get": {
        "summary": "list concerts",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      },
      "post": {
        "summary": "create concert",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "type": "string",
            "description": "Bearer token"
          },
          {
            "name": "concert_params",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "concert": {
                  "type": "object",
                  "properties": {
                    "name": {
                      "type": "string"
                    },
                    "band": {
                      "type": "string"
                    },
                    "image": {
                      "type": "string"
                    },
                    "description": {
                      "type": "string"
                    },
                    "total_seats": {
                      "type": "integer"
                    },
                    "artist": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "name",
                    "band",
                    "image",
                    "description",
                    "total_seats",
                    "artist"
                  ]
                },
                "concert_hall": {
                  "type": "object",
                  "properties": {
                    "city_id": {
                      "type": "integer"
                    },
                    "date": {
                      "type": "string",
                      "format": "date"
                    }
                  },
                  "required": [
                    "city_id",
                    "date"
                  ]
                }
              },
              "required": [
                "concert",
                "concert_hall"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/api/v1/concerts/{id}": {
      "parameters": [
        {
          "name": "id",
          "in": "path",
          "type": "string",
          "description": "id",
          "required": true
        }
      ],
      "get": {
        "summary": "show concert",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      },
      "delete": {
        "summary": "delete concert",
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/api/v1/reservations": {
      "get": {
        "summary": "list reservations",
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "type": "string",
            "description": "Bearer token"
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/api/v1/login": {
      "post": {
        "summary": "create session",
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "credentials",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "username": {
                  "type": "string"
                },
                "password": {
                  "type": "string"
                }
              },
              "required": [
                "username",
                "password"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    },
    "/api/v1/register": {
      "post": {
        "summary": "create user",
        "consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "user",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "name": {
                  "type": "string"
                },
                "username": {
                  "type": "string"
                },
                "email": {
                  "type": "string",
                  "format": "email"
                },
                "password": {
                  "type": "string"
                },
                "password_confirmation": {
                  "type": "string"
                }
              },
              "required": [
                "name",
                "username",
                "email",
                "password",
                "password_confirmation"
              ]
            }
          }
        ],
        "responses": {
          "200": {
            "description": "successful"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "http://{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "127.0.0.1:3000/"
        }
      }
    }
  ]
}